package store

import (
	"embed"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// autoIDExpr is the dialect-specific autoincrement PK column definition,
// substituted for the {{.AutoID}} macro in migration files.
func autoIDExpr(pg bool) string {
	if pg {
		return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	return "INTEGER PRIMARY KEY AUTOINCREMENT"
}

type migration struct {
	version int
	name    string
	sql     string
}

// hooks holds Go steps that run inside a migration's transaction, keyed by
// version, after that version's .sql (if any). Registered from migration_hooks.go.
var hooks = map[int]func(tx *dbtx, pg bool) error{}

// registerHook binds a Go step to a migration version. Called from an init()
// in migration_hooks.go.
func registerHook(version int, fn func(tx *dbtx, pg bool) error) { hooks[version] = fn }

// loadMigrations reads and orders migrations/NNN_*.sql from the embed FS.
func loadMigrations() ([]migration, error) {
	entries, err := migrationFS.ReadDir("migrations")
	if err != nil {
		return nil, fmt.Errorf("read migrations dir: %w", err)
	}
	var out []migration
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		num, _, ok := strings.Cut(e.Name(), "_")
		if !ok {
			return nil, fmt.Errorf("migration %q: expected NNN_name.sql", e.Name())
		}
		v, err := strconv.Atoi(num)
		if err != nil {
			return nil, fmt.Errorf("migration %q: bad version: %w", e.Name(), err)
		}
		b, err := migrationFS.ReadFile("migrations/" + e.Name())
		if err != nil {
			return nil, fmt.Errorf("read migration %s: %w", e.Name(), err)
		}
		out = append(out, migration{version: v, name: e.Name(), sql: string(b)})
	}
	// hook-only versions: a registered hook with no matching .sql file becomes
	// a migration with an empty script (splitSQL("") == nil → 0 statements →
	// the runner still fires hooks[v]).
	haveFile := map[int]bool{}
	for _, m := range out {
		haveFile[m.version] = true
	}
	for v := range hooks {
		if !haveFile[v] {
			out = append(out, migration{version: v, name: fmt.Sprintf("%03d_hook", v), sql: ""})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].version < out[j].version })
	return out, nil
}

// runMigrations applies every migration whose version is not yet recorded
// in schema_migrations, each in its own transaction, lowest version first.
func (s *Store) runMigrations() error { return s.runMigrationsFiltered(0) }

// runMigrationsUpTo applies migrations with version <= max (test helper).
func (s *Store) runMigrationsUpTo(max int) error { return s.runMigrationsFiltered(max) }

// runMigrationsFiltered applies every unapplied migration whose version is
// <= max (max <= 0 means no limit), each in its own transaction, lowest
// version first. A Go hook registered for a version runs inside that
// version's transaction, after the .sql statements and before the version is
// recorded in schema_migrations.
func (s *Store) runMigrationsFiltered(max int) error {
	if _, err := s.db.Exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
		version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)`); err != nil {
		return fmt.Errorf("schema_migrations: %w", err)
	}
	applied := map[int]bool{}
	rows, err := s.db.Query(`SELECT version FROM schema_migrations`)
	if err != nil {
		return err
	}
	for rows.Next() {
		var v int
		if err := rows.Scan(&v); err != nil {
			rows.Close()
			return fmt.Errorf("scan applied version: %w", err)
		}
		applied[v] = true
	}
	rows.Close()

	migs, err := loadMigrations()
	if err != nil {
		return fmt.Errorf("load migrations: %w", err)
	}
	macro := autoIDExpr(s.db.pg)
	for _, m := range migs {
		if applied[m.version] || (max > 0 && m.version > max) {
			continue
		}
		script := strings.ReplaceAll(m.sql, "{{.AutoID}}", macro)
		tx, err := s.db.Begin()
		if err != nil {
			return fmt.Errorf("begin %s: %w", m.name, err)
		}
		for _, stmt := range splitSQL(script) {
			if _, err := tx.Exec(stmt); err != nil {
				tx.Rollback()
				return fmt.Errorf("migration %s: %s: %w", m.name, firstLine(stmt), err)
			}
		}
		if hook := hooks[m.version]; hook != nil {
			if err := hook(tx, s.db.pg); err != nil {
				tx.Rollback()
				return fmt.Errorf("migration %s hook: %w", m.name, err)
			}
		}
		if _, err := tx.Exec(`INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)`,
			m.version, time.Now().UTC().Format(time.RFC3339)); err != nil {
			tx.Rollback()
			return fmt.Errorf("record %s: %w", m.name, err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit %s: %w", m.name, err)
		}
	}
	return nil
}

// splitSQL breaks a multi-statement script on ';' at statement level.
// Migration files must not contain ';' inside string literals.
func splitSQL(script string) []string {
	var out []string
	for _, s := range strings.Split(script, ";") {
		if strings.TrimSpace(s) != "" {
			out = append(out, s)
		}
	}
	return out
}
